import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const DATA_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'database_query',
    label: NODE.dataSourceQuery.label,
    category: CONFIG.categories.data,
    icon: 'database',
    type: 'database_write',
    description: NODE.dataSourceQuery.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.dataSourceQuery.label,
      enabled: true,
      datasource: 'qo_hrms_prod',
      method: 'All Methods',
      query: 'GET /employees',
      returnMode: 'all rows',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.dataSourceQuery.label),
      {
        key: 'datasource',
        label: CONFIG.fields.dataSource,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'method',
        label: CONFIG.fields.method,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.queryMethod,
      },
      {
        key: 'query',
        label: CONFIG.fields.queryEndpoint,
        type: 'select',
        tab: 'action',
        required: true,
        hint: CONFIG.hints.dataSourceQueries,
      },
      {
        key: 'filters',
        label: CONFIG.fields.filters,
        type: 'ruleBuilder',
        tab: 'action',
      },
      {
        key: 'values',
        label: CONFIG.fields.values,
        type: 'mapping',
        tab: 'action',
      },
      {
        key: 'limit',
        label: CONFIG.fields.limit,
        type: 'number',
        tab: 'action',
      },
      {
        key: 'requireFilterForMutations',
        label: CONFIG.fields.requireFilterForMutations,
        type: 'toggle',
        tab: 'validation',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.dataSourceRequired, CONFIG.validationRules.queryEndpointRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'create_audit_log',
    label: NODE.createAuditLog.label,
    category: CONFIG.categories.database,
    icon: 'database',
    type: 'database_write',
    description: NODE.createAuditLog.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.createAuditLog.label,
      enabled: true,
      auditTable: 'workflow_audit_logs',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.createAuditLog.label),
      {
        key: 'auditTable',
        label: CONFIG.fields.auditTable,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'auditPayload',
        label: CONFIG.fields.auditPayload,
        type: 'mapping',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.auditTableRequired, CONFIG.validationRules.auditPayloadRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'transform_data',
    label: NODE.transformData.label,
    category: CONFIG.categories.dataTransform,
    icon: 'shuffle',
    type: 'custom_function',
    description: NODE.transformData.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.transformData.label,
      enabled: true,
      transformMode: 'visual mapping',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.transformData.label),
      {
        key: 'transformMode',
        label: CONFIG.fields.transformMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.transformMode,
      },
      {
        key: 'inputSchema',
        label: CONFIG.fields.inputSchema,
        type: 'schema',
        tab: 'action',
      },
      {
        key: 'outputSchema',
        label: CONFIG.fields.outputSchema,
        type: 'schema',
        tab: 'action',
      },
      {
        key: 'mappingRules',
        label: CONFIG.fields.mappingRules,
        type: 'mapping',
        tab: 'action',
      },
      {
        key: 'function',
        label: CONFIG.fields.function,
        type: 'code',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.transformModeRequired, CONFIG.validationRules.transformRuleRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'upload_cdn',
    label: NODE.uploadCdn.label,
    category: CONFIG.categories.storage,
    icon: 'cloud-upload',
    type: 'api_call',
    description: NODE.uploadCdn.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.uploadCdn.label,
      enabled: true,
      visibility: 'private',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.uploadCdn.label),
      {
        key: 'fileSource',
        label: CONFIG.fields.fileSource,
        type: 'fileMapping',
        tab: 'action',
        required: true,
      },
      {
        key: 'bucket',
        label: CONFIG.fields.bucket,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'path',
        label: CONFIG.fields.uploadPath,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'visibility',
        label: CONFIG.fields.visibility,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.visibility,
      },
      {
        key: 'metadataFields',
        label: CONFIG.fields.metadataFields,
        type: 'keyValue',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [
      CONFIG.validationRules.fileSourceRequired,
      CONFIG.validationRules.bucketRequired,
      CONFIG.validationRules.uploadPathRequired,
    ],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
