import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const EVENT_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'filter_event',
    label: NODE.filterEvent.label,
    category: CONFIG.categories.eventProcessing,
    icon: 'workflow',
    type: 'condition',
    description: NODE.filterEvent.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.filterEvent.label,
      enabled: true,
      matchType: 'all',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.filterEvent.label),
      {
        key: 'conditions',
        label: CONFIG.fields.eventConditions,
        type: 'ruleBuilder',
        tab: 'action',
        required: true,
      },
      {
        key: 'matchType',
        label: CONFIG.fields.matchType,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.allAnyCustom,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.eventConditionRequired],
    ports: { inputs: 1, outputs: 2, outputLabels: [CONFIG.ports.matched, CONFIG.ports.ignored] },
    paletteVisible: true,
  },
{
    id: 'route_event',
    label: NODE.routeEvent.label,
    category: CONFIG.categories.eventProcessing,
    icon: 'split',
    type: 'condition',
    description: NODE.routeEvent.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.routeEvent.label,
      enabled: true,
      routeBy: '{{event.type}}',
      defaultCase: 'default',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.routeEvent.label),
      {
        key: 'routeBy',
        label: CONFIG.fields.routeBy,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: '{{event.type}}',
      },
      {
        key: 'routes',
        label: CONFIG.fields.routes,
        type: 'keyValue',
        tab: 'action',
        required: true,
      },
      {
        key: 'defaultCase',
        label: CONFIG.fields.defaultCase,
        type: 'text',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.routeSourceRequired, CONFIG.validationRules.routeRequired],
    ports: { inputs: 1, outputs: 2, outputLabels: [CONFIG.ports.matched, CONFIG.ports.default] },
    paletteVisible: true,
  },
{
    id: 'transform_event_payload',
    label: NODE.transformEventPayload.label,
    category: CONFIG.categories.eventProcessing,
    icon: 'shuffle',
    type: 'custom_function',
    description: NODE.transformEventPayload.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.transformEventPayload.label,
      enabled: true,
      transformMode: 'visual mapping',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.transformEventPayload.label),
      {
        key: 'transformMode',
        label: CONFIG.fields.transformMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.transformMode,
      },
      {
        key: 'mappingRules',
        label: CONFIG.fields.mappingRules,
        type: 'mapping',
        tab: 'action',
      },
      {
        key: 'function',
        label: CONFIG.fields.function,
        type: 'code',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.transformModeRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'deduplicate_event',
    label: NODE.deduplicateEvent.label,
    category: CONFIG.categories.eventProcessing,
    icon: 'check',
    type: 'condition',
    description: NODE.deduplicateEvent.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.deduplicateEvent.label,
      enabled: true,
      dedupeKey: '{{event.id}}',
      ttl: '24h',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.deduplicateEvent.label),
      {
        key: 'dedupeKey',
        label: CONFIG.fields.deduplicationKey,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: '{{event.id}}',
      },
      {
        key: 'ttl',
        label: CONFIG.fields.rememberFor,
        type: 'duration',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.dedupeKeyRequired],
    ports: { inputs: 1, outputs: 2, outputLabels: [CONFIG.ports.new, CONFIG.ports.duplicate] },
    paletteVisible: true,
  },
{
    id: 'wait_delay',
    label: NODE.waitDelay.label,
    category: CONFIG.categories.eventProcessing,
    icon: 'calendar',
    type: 'delay',
    description: NODE.waitDelay.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.waitDelay.label,
      enabled: true,
      duration: '5m',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.waitDelay.label),
      {
        key: 'duration',
        label: CONFIG.fields.duration,
        type: 'duration',
        tab: 'action',
        required: true,
      },
      {
        key: 'resumePolicy',
        label: CONFIG.fields.resumePolicy,
        type: 'select',
        tab: 'action',
        options: CONFIG.options.resumePolicy,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.delayDurationRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
