import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const FORM_ACTION_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'validate_form_data',
    label: NODE.validateFormData.label,
    category: CONFIG.categories.formActions,
    icon: 'check',
    type: 'condition',
    description: NODE.validateFormData.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.validateFormData.label,
      enabled: true,
      validationMode: 'rules',
      failureMessage: CONFIG.defaults.fixHighlightedFields,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.validateFormData.label),
      {
        key: 'validationMode',
        label: CONFIG.fields.validationMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.validationMode,
      },
      {
        key: 'rules',
        label: CONFIG.fields.validationRules,
        type: 'ruleBuilder',
        tab: 'action',
        required: true,
      },
      {
        key: 'failureMessage',
        label: CONFIG.fields.failureMessage,
        type: 'textarea',
        tab: 'validation',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.validationRuleRequired],
    ports: { inputs: 1, outputs: 2, outputLabels: [CONFIG.ports.valid, CONFIG.ports.invalid] },
    paletteVisible: true,
  },
{
    id: 'update_form_record',
    label: NODE.updateFormRecord.label,
    category: CONFIG.categories.formActions,
    icon: 'database',
    type: 'database_write',
    description: NODE.updateFormRecord.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.updateFormRecord.label,
      enabled: true,
      recordSource: '{{start.record.id}}',
      conflictMode: 'merge',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.updateFormRecord.label),
      {
        key: 'recordSource',
        label: CONFIG.fields.recordSource,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: '{{start.record.id}}',
      },
      {
        key: 'fieldValues',
        label: CONFIG.fields.fieldValues,
        type: 'mapping',
        tab: 'action',
        required: true,
      },
      {
        key: 'conflictMode',
        label: CONFIG.fields.conflictMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.conflictMode,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.recordSourceRequired, CONFIG.validationRules.fieldValueRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'show_hide_fields',
    label: NODE.showHideFields.label,
    category: CONFIG.categories.formActions,
    icon: 'list',
    type: 'notification',
    description: NODE.showHideFields.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.showHideFields.label,
      enabled: true,
      fieldAction: 'hide',
      applyMode: 'always',
      preserveHiddenValues: true,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.showHideFields.label),
      {
        key: 'fields',
        label: CONFIG.fields.fields,
        type: 'multiSelect',
        tab: 'action',
        required: true,
        hint: CONFIG.hints.fields,
      },
      {
        key: 'fieldAction',
        label: CONFIG.fields.fieldAction,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.fieldAction,
      },
      {
        key: 'applyMode',
        label: CONFIG.fields.applyMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.applyMode,
      },
      {
        key: 'condition',
        label: CONFIG.fields.condition,
        type: 'ruleBuilder',
        tab: 'action',
        hint: CONFIG.hints.showHideCondition,
      },
      {
        key: 'preserveHiddenValues',
        label: CONFIG.fields.preserveHiddenValues,
        type: 'toggle',
        tab: 'validation',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired, CONFIG.validationRules.fieldActionRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'show_field',
    label: NODE.showField.label,
    category: CONFIG.categories.fieldActions,
    icon: 'list',
    type: 'notification',
    description: NODE.showField.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.showField.label,
      enabled: true,
      conditionType: CONFIG.options.conditionType[0],
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.showField.label),
      targetFieldField(),
      ...fieldActionCriteriaFields,
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'hide_field',
    label: NODE.hideField.label,
    category: CONFIG.categories.fieldActions,
    icon: 'list',
    type: 'notification',
    description: NODE.hideField.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.hideField.label,
      enabled: true,
      conditionType: CONFIG.options.conditionType[0],
      preserveValue: true,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.hideField.label),
      targetFieldField(),
      ...fieldActionCriteriaFields,
      {
        key: 'preserveValue',
        label: CONFIG.fields.preserveHiddenValue,
        type: 'toggle',
        tab: 'validation',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'enable_field',
    label: NODE.enableField.label,
    category: CONFIG.categories.fieldActions,
    icon: 'check',
    type: 'notification',
    description: NODE.enableField.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.enableField.label,
      enabled: true,
      conditionType: CONFIG.options.conditionType[0],
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.enableField.label),
      targetFieldField(),
      ...fieldActionCriteriaFields,
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'disable_field',
    label: NODE.disableField.label,
    category: CONFIG.categories.fieldActions,
    icon: 'x',
    type: 'notification',
    description: NODE.disableField.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.disableField.label,
      enabled: true,
      conditionType: CONFIG.options.conditionType[0],
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.disableField.label),
      targetFieldField(),
      ...fieldActionCriteriaFields,
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'set_field_value',
    label: NODE.setFieldValue.label,
    category: CONFIG.categories.fieldActions,
    icon: 'shuffle',
    type: 'notification',
    description: NODE.setFieldValue.description,
    allowedBuilders: ['form-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.setFieldValue.label,
      enabled: true,
      valueType: CONFIG.defaults.dynamic,
      autoMap: true,
      conditionType: CONFIG.options.conditionType[0],
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.setFieldValue.label),
      targetFieldField(),
      {
        key: 'valueType',
        label: CONFIG.fields.valueType,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.valueType,
      },
      {
        key: 'staticValue',
        label: CONFIG.fields.staticValue,
        type: 'text',
        tab: 'action',
      },
      {
        key: 'valueMapping',
        label: CONFIG.fields.valueMapping,
        type: 'mapping',
        tab: 'action',
      },
      {
        key: 'formula',
        label: CONFIG.fields.expressionBuilder,
        type: 'code',
        tab: 'action',
      },
      {
        key: 'autoMap',
        label: CONFIG.fields.autoMap,
        type: 'toggle',
        tab: 'action',
      },
      ...fieldActionCriteriaFields,
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetFieldRequired, CONFIG.validationRules.valueTypeRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
