import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const INTEGRATION_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'api_query',
    label: NODE.apiQuery.label,
    category: CONFIG.categories.api,
    icon: 'globe',
    type: 'api_call',
    description: NODE.apiQuery.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.apiQuery.label,
      enabled: true,
      method: 'GET',
      url: 'https://api.example.com',
      authType: 'none',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.apiQuery.label),
      {
        key: 'method',
        label: CONFIG.fields.method,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.httpMethod,
      },
      {
        key: 'url',
        label: CONFIG.fields.url,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: CONFIG.placeholders.apiUrl,
      },
      {
        key: 'authType',
        label: CONFIG.fields.authType,
        type: 'select',
        tab: 'action',
        options: CONFIG.options.authType,
      },
      {
        key: 'headers',
        label: CONFIG.fields.headers,
        type: 'keyValue',
        tab: 'action',
      },
      {
        key: 'queryParams',
        label: CONFIG.fields.queryParams,
        type: 'keyValue',
        tab: 'action',
      },
      {
        key: 'body',
        label: CONFIG.fields.requestBody,
        type: 'json',
        tab: 'action',
      },
      {
        key: 'timeout',
        label: CONFIG.fields.timeout,
        type: 'duration',
        tab: 'errorHandling',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.methodRequired, CONFIG.validationRules.urlRequired, CONFIG.validationRules.urlValidRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'http_request',
    label: NODE.httpRequest.label,
    category: CONFIG.categories.api,
    icon: 'send',
    type: 'api_call',
    description: NODE.httpRequest.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.httpRequest.label,
      enabled: true,
      method: 'POST',
      url: 'https://api.example.com/action',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.httpRequest.label),
      {
        key: 'method',
        label: CONFIG.fields.method,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.httpMethod,
      },
      {
        key: 'url',
        label: CONFIG.fields.url,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'headers',
        label: CONFIG.fields.headers,
        type: 'keyValue',
        tab: 'action',
      },
      {
        key: 'queryParams',
        label: CONFIG.fields.queryParams,
        type: 'keyValue',
        tab: 'action',
      },
      {
        key: 'body',
        label: CONFIG.fields.body,
        type: 'json',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.methodRequired, CONFIG.validationRules.urlRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'webhook',
    label: NODE.webhook.label,
    category: CONFIG.categories.integrations,
    icon: 'send',
    type: 'api_call',
    description: NODE.webhook.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.webhook.label,
      enabled: true,
      method: 'POST',
      retryPolicy: true,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.webhook.label),
      {
        key: 'webhookUrl',
        label: CONFIG.fields.webhookUrl,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: CONFIG.placeholders.webhookUrl,
      },
      {
        key: 'payload',
        label: CONFIG.fields.payload,
        type: 'json',
        tab: 'action',
        required: true,
      },
      {
        key: 'headers',
        label: CONFIG.fields.headers,
        type: 'keyValue',
        tab: 'action',
      },
      {
        key: 'retryPolicy',
        label: CONFIG.fields.retryPolicy,
        type: 'toggle',
        tab: 'errorHandling',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.webhookUrlRequired, CONFIG.validationRules.payloadRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
