import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const NOTIFICATION_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'channel_switch',
    label: NODE.channelSwitch.label,
    category: CONFIG.categories.messaging,
    icon: 'split',
    type: 'condition',
    description: NODE.channelSwitch.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.channelSwitch.label,
      enabled: true,
      channelSource: '{{start.channel}}',
      defaultCase: 'default',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.channelSwitch.label),
      {
        key: 'channelSource',
        label: CONFIG.fields.channelSource,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: '{{start.channel}}',
      },
      {
        key: 'cases',
        label: CONFIG.fields.cases,
        type: 'keyValue',
        tab: 'action',
        required: true,
      },
      {
        key: 'defaultCase',
        label: CONFIG.fields.defaultCase,
        type: 'text',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [
      CONFIG.validationRules.channelSourceRequired,
      CONFIG.validationRules.caseRequired,
      CONFIG.validationRules.defaultCaseRequired,
    ],
    ports: { inputs: 1, outputs: 2, outputLabels: [CONFIG.ports.matched, CONFIG.ports.default] },
    paletteVisible: true,
  },
{
    id: 'send_email',
    label: NODE.sendEmail.label,
    category: CONFIG.categories.notifications,
    icon: 'mail',
    type: 'email',
    description: NODE.sendEmail.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.sendEmail.label,
      enabled: true,
      subject: CONFIG.defaults.workflowNotification,
      bodyType: CONFIG.options.bodyTypeHtml,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.sendEmail.label),
      {
        key: 'sender',
        label: CONFIG.fields.sender,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'to',
        label: CONFIG.fields.to,
        type: 'emailList',
        tab: 'action',
        required: true,
      },
      {
        key: 'cc',
        label: CONFIG.fields.cc,
        type: 'emailList',
        tab: 'action',
      },
      {
        key: 'bcc',
        label: CONFIG.fields.bcc,
        type: 'emailList',
        tab: 'action',
      },
      {
        key: 'subject',
        label: CONFIG.fields.subject,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'body',
        label: CONFIG.fields.body,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      {
        key: 'attachments',
        label: CONFIG.fields.attachments,
        type: 'fileMapping',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.recipientRequired, CONFIG.validationRules.subjectRequired, CONFIG.validationRules.bodyRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'send_sms',
    label: NODE.sendSms.label,
    category: CONFIG.categories.notifications,
    icon: 'message-square',
    type: 'notification',
    description: NODE.sendSms.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.sendSms.label,
      enabled: true,
      message: CONFIG.defaults.smsReceived,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.sendSms.label),
      {
        key: 'provider',
        label: CONFIG.fields.provider,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.provider,
      },
      {
        key: 'to',
        label: CONFIG.fields.phoneNumbers,
        type: 'textarea',
        tab: 'action',
        required: true,
        placeholder: CONFIG.placeholders.phoneNumber,
      },
      {
        key: 'message',
        label: CONFIG.fields.message,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.phoneRequired, CONFIG.validationRules.messageRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'send_notification',
    label: NODE.sendNotification.label,
    category: CONFIG.categories.notifications,
    icon: 'bell',
    type: 'notification',
    description: NODE.sendNotification.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.sendNotification.label,
      enabled: true,
      title: CONFIG.defaults.workflowNotification,
      message: CONFIG.defaults.workflowNotificationAttention,
      severity: 'info',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.sendNotification.label),
      {
        key: 'recipients',
        label: CONFIG.fields.recipients,
        type: 'multiSelect',
        tab: 'action',
        required: true,
      },
      {
        key: 'title',
        label: CONFIG.fields.title,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'message',
        label: CONFIG.fields.message,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      {
        key: 'severity',
        label: CONFIG.fields.severity,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.severity,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.notificationRecipientRequired, CONFIG.validationRules.notificationMessageRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'redirect_url',
    label: NODE.redirectUrl.label,
    category: CONFIG.categories.notifications,
    icon: 'external-link',
    type: 'notification',
    description: NODE.redirectUrl.description,
    allowedBuilders: ['form-builder', 'page-builder', 'report-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.redirectUrl.label,
      enabled: true,
      targetUrl: 'https://example.com',
      openMode: 'same tab',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.redirectUrl.label),
      {
        key: 'targetUrl',
        label: CONFIG.fields.targetUrl,
        type: 'text',
        tab: 'action',
        required: true,
        placeholder: CONFIG.placeholders.thankYouUrl,
      },
      {
        key: 'openMode',
        label: CONFIG.fields.openMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.openMode,
      },
      {
        key: 'queryParams',
        label: CONFIG.fields.queryParams,
        type: 'keyValue',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetUrlRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'show_notification',
    label: NODE.showNotification.label,
    category: CONFIG.categories.uiFeedback,
    icon: 'bell',
    type: 'notification',
    description: NODE.showNotification.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.showNotification.label,
      enabled: true,
      message: CONFIG.defaults.actionCompleted,
      severity: 'success',
      displayTarget: 'toast',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.showNotification.label),
      {
        key: 'message',
        label: CONFIG.fields.message,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      {
        key: 'severity',
        label: CONFIG.fields.severity,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.severity,
      },
      {
        key: 'displayTarget',
        label: CONFIG.fields.displayTarget,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.displayTarget,
      },
      {
        key: 'duration',
        label: CONFIG.fields.duration,
        type: 'duration',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.messageRequired, CONFIG.validationRules.severityRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'show_success_message',
    label: NODE.showSuccessMessage.label,
    category: CONFIG.categories.notifications,
    icon: 'check',
    type: 'notification',
    description: NODE.showSuccessMessage.description,
    allowedBuilders: ALL_BUILDERS,
    defaultConfig: {
      label: NODE.showSuccessMessage.label,
      enabled: true,
      message: CONFIG.defaults.successMessage,
      displayTarget: 'toast',
      duration: '4s',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.showSuccessMessage.label),
      {
        key: 'message',
        label: CONFIG.fields.message,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      {
        key: 'displayTarget',
        label: CONFIG.fields.displayTarget,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.displayTargetNoWidget,
      },
      {
        key: 'duration',
        label: CONFIG.fields.duration,
        type: 'duration',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.successMessageRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
