import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const PAGE_BUILDER_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'page_trigger',
    label: NODE.pageTrigger.label,
    category: CONFIG.categories.pageBuilder,
    icon: 'panel-top',
    type: 'trigger',
    description: NODE.pageTrigger.description,
    allowedBuilders: ['page-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.pageTrigger.label,
      enabled: true,
      event: 'page.load',
    },
    configTabs: TRIGGER_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.pageTrigger.label),
      {
        key: 'page',
        label: CONFIG.fields.page,
        type: 'select',
        tab: 'trigger',
        required: true,
      },
      {
        key: 'widget',
        label: CONFIG.fields.widget,
        type: 'select',
        tab: 'trigger',
      },
      {
        key: 'event',
        label: CONFIG.fields.event,
        type: 'select',
        tab: 'trigger',
        required: true,
        options: CONFIG.options.event,
      },
      {
        key: 'payloadSchema',
        label: CONFIG.fields.payloadSchema,
        type: 'schema',
        tab: 'trigger',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.pageRequired, CONFIG.validationRules.eventRequired],
    ports: { inputs: 0, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'set_widget_data',
    label: NODE.setWidgetData.label,
    category: CONFIG.categories.pageBuilder,
    icon: 'blocks',
    type: 'database_write',
    description: NODE.setWidgetData.description,
    allowedBuilders: ['page-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.setWidgetData.label,
      enabled: true,
      refreshStrategy: 'replace',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.setWidgetData.label),
      {
        key: 'targetPage',
        label: CONFIG.fields.targetPage,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'targetWidget',
        label: CONFIG.fields.targetWidget,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'widgetData',
        label: CONFIG.fields.widgetData,
        type: 'mapping',
        tab: 'action',
        required: true,
      },
      {
        key: 'refreshStrategy',
        label: CONFIG.fields.refreshStrategy,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.refreshStrategy,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetWidgetRequired, CONFIG.validationRules.widgetDataRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'navigate',
    label: NODE.navigate.label,
    category: CONFIG.categories.pageBuilder,
    icon: 'navigation',
    type: 'notification',
    description: NODE.navigate.description,
    allowedBuilders: ['form-builder', 'page-builder', 'report-builder', 'workflow-builder'],
    defaultConfig: {
      label: NODE.navigate.label,
      enabled: true,
      targetType: 'page',
      navigationMode: 'push',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.navigate.label),
      {
        key: 'targetType',
        label: CONFIG.fields.targetType,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.targetType,
      },
      {
        key: 'target',
        label: CONFIG.fields.target,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'navigationMode',
        label: CONFIG.fields.navigationMode,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.navigationMode,
      },
      {
        key: 'queryParams',
        label: CONFIG.fields.queryParams,
        type: 'keyValue',
        tab: 'action',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.targetRequired, CONFIG.validationRules.navigationModeRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
