import {
  ACTION_CONFIG_TABS,
  ALL_BUILDERS,
  TRIGGER_CONFIG_TABS,
  fieldActionCriteriaFields,
  generalFields,
  standardMappingFields,
  targetFieldField,
} from './workflow-node-fields.config';
import { WorkflowNodeDefinition } from './workflow-node.types';
import { WORKFLOW_LANGUAGE } from '../../services/workflow-language';

const NODE = WORKFLOW_LANGUAGE.nodes;
const CONFIG = WORKFLOW_LANGUAGE.nodeConfig;

export const SCHEDULER_NODES: readonly WorkflowNodeDefinition[] = [
{
    id: 'schedule_notification',
    label: NODE.notification.label,
    category: CONFIG.categories.notifications,
    icon: 'bell',
    type: 'notification',
    description: NODE.notification.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.notification.label,
      enabled: true,
      channel: CONFIG.options.channel[0],
      recipients: CONFIG.defaults.hrTeam,
      subject: CONFIG.defaults.scheduledNotificationSubject,
      message: CONFIG.defaults.scheduledWorkflowRan,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.notification.label),
      {
        key: 'channel',
        label: CONFIG.fields.channel,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.channel,
      },
      {
        key: 'recipients',
        label: CONFIG.fields.recipients,
        type: 'emailList',
        tab: 'action',
        required: true,
      },
      {
        key: 'subject',
        label: CONFIG.fields.subject,
        type: 'text',
        tab: 'action',
      },
      {
        key: 'message',
        label: CONFIG.fields.message,
        type: 'textarea',
        tab: 'action',
        required: true,
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.channelRequired, CONFIG.validationRules.notificationMessageRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'schedule_data_access',
    label: NODE.dataAccess.label,
    category: CONFIG.categories.data,
    icon: 'database',
    type: 'database_write',
    description: NODE.dataAccess.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.dataAccess.label,
      enabled: true,
      operation: CONFIG.options.operation[0],
      targetForm: CONFIG.defaults.addEmployeeForm,
      matchRule: '',
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.dataAccess.label),
      {
        key: 'operation',
        label: CONFIG.fields.operation,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.operation,
      },
      {
        key: 'targetForm',
        label: CONFIG.fields.targetForm,
        type: 'select',
        tab: 'action',
        required: true,
      },
      {
        key: 'matchRule',
        label: CONFIG.fields.matchFilterRule,
        type: 'ruleBuilder',
        tab: 'validation',
      },
      {
        key: 'fieldMapping',
        label: CONFIG.fields.fieldMapping,
        type: 'mapping',
        tab: 'inputMapping',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.dataAccessOperationRequired, CONFIG.validationRules.targetFormRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  },
{
    id: 'schedule_function',
    label: NODE.function.label,
    category: CONFIG.categories.functions,
    icon: 'code',
    type: 'custom_function',
    description: NODE.function.description,
    allowedBuilders: ['workflow-builder'],
    defaultConfig: {
      label: NODE.function.label,
      enabled: true,
      runtime: CONFIG.options.runtime[0],
      functionName: CONFIG.defaults.scheduledFunctionName,
      timeout: 30,
    },
    configTabs: ACTION_CONFIG_TABS,
    configSchema: [
      ...generalFields(NODE.function.label),
      {
        key: 'runtime',
        label: CONFIG.fields.runtime,
        type: 'select',
        tab: 'action',
        required: true,
        options: CONFIG.options.runtime,
      },
      {
        key: 'functionName',
        label: CONFIG.fields.functionName,
        type: 'text',
        tab: 'action',
        required: true,
      },
      {
        key: 'inputParameters',
        label: CONFIG.fields.inputParameters,
        type: 'keyValue',
        tab: 'inputMapping',
      },
      {
        key: 'script',
        label: CONFIG.fields.script,
        type: 'code',
        tab: 'action',
      },
      {
        key: 'timeout',
        label: CONFIG.fields.timeoutSeconds,
        type: 'number',
        tab: 'advanced',
      },
      ...standardMappingFields,
    ],
    validationRules: [CONFIG.validationRules.functionNameRequired, CONFIG.validationRules.runtimeRequired],
    ports: { inputs: 1, outputs: 1 },
    paletteVisible: true,
  }
];
