export const DATASOURCES_LANG = {
  common: {
    allCategories: 'All Categories',
    allStatus: 'All Status',
    connected: 'Connected',
    expiredToken: 'Expired Token',
    error: 'Error',
    notConnected: 'Not Connected',
    active: 'ACTIVE',
    inactive: 'INACTIVE',
    authOk: 'OK',
    authExpired: 'Expired',
    save: 'Save',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    back: 'Back',
    backArrow: '← Back',
    delete: 'Delete',
    edit: 'Edit',
    clear: 'Clear',
    close: 'Close',
    remove: 'Remove',
    expand: 'Expand',
    collapse: 'Collapse',
    schema: 'Schema',
    detail: 'Detail',
    optional: 'Optional',
    unique: 'Unique',
    required: 'Required',
    testConnection: 'Test Connection',
    run: 'Run',
    debug: 'Debug',
    testConfiguration: 'Test Configuration',
    testAll: 'Test All',
    externalApis: 'External APIs',
    status: 'Status',
    sync: 'Sync',
    datasourceConfiguration: 'Datasource Configuration',
    saveDatasource: 'Save Datasource',
    configureIntegration: 'Configure Integration',
    configure: 'Configure',
    configureAuthWorkspace: 'Configure authentication and workspace access for this external API integration.',
    loadingIntegrationTitle: 'Loading integration',
    loadingIntegrationDescription: 'Preparing the saved connector settings.',
    configurationTest: 'Configuration Test',
    dataSources: 'Data Sourcdes',
    dataSourcesEyebrow: 'Data Sources',
    dataSourcesDescription: 'Connect external data to this application. Each connection tracks 10 health metrics. Click Expand to view individual endpoint metrics.',
    dataSourcesInfoCard: '10 health metrics tracked per data source and per endpoint: Availability, Latency (p50/p95/p99), Throughput, Rate Limit, Auth Status, Error Rates, Data Freshness, and Access Logs.',
    addDataSource: '+ Add Data Source',
    searchDatasources: 'Search datasources...',
    noDatasourcesFound: 'No datasources found',
    tryDifferentDatasourceSearch: 'Try a different datasource search.',
    addDataSourceEyebrow: 'Add Data Source',
    selectDatasource: 'Select Datasource',
    selectDatasourceDescription: 'Choose a database or API connector for this Builder workspace.',
    apisSection: 'APIs',
    databasesSection: 'Databases',
    datasourceNotFound: 'Datasource not found.',
    datasourceConnectorNotFound: 'Datasource connector not found.',
    noActiveDataSourcesToTest: 'No active data sources are available to test.',
    activeDataSourcesTested: 'Active data sources tested successfully.',
    datasourceInactiveActivateBeforeTesting: '{name} is inactive. Activate it before testing.',
    datasourceTestedSuccessfully: '{name} tested successfully.',
    connectionTestSucceeded: 'Connection test succeeded.',
    datasourceUpdatedSuccessfully: '{name} updated successfully.',
    datasourceAdded: '{name} added to Data Sources.',
    datasourceRunPreviewExecuted: 'Datasource run preview executed.',
    datasourceInactiveActivateBeforeOpeningSchema: '{name} is inactive. Activate it before opening schema.',
    activateDatasourceBeforeAddingQuery: 'Activate the datasource before adding a query.',
    datasourceInactiveActivateBeforeEditingQuery: '{name} is inactive. Activate it before editing queries.',
    datasourceDeletedSuccessfully: '{name} deleted.',
    markedActive: '{name} marked active.',
    markedInactive: '{name} marked inactive.',
    desktopViewportRequiredTitle: 'Desktop view required',
    desktopViewportRequiredDescription: 'Builder works on desktop screens only. Open this workspace on a viewport that is at least 1024 pixels wide.',
    returnToDataSources: 'Return to Data Sources',
    complianceTitle: 'Compliance',
    complianceDescription: 'Retention, encryption, credential rotation, and policy checks for each datasource will appear here.',
    dataLogsTitle: 'Data logs',
    dataLogsDescription: 'Audit trails for datasource syncs, refreshes, retries, and query execution will appear here.',
  },
  card: {
    endpointsHeading: 'Endpoints / Queries · {name} · Saved: {count}',
    addQueryLabel: 'Add Query',
    colQueryEndpoint: 'Query / Endpoint',
    colMethod: 'Method',
    colCalls: 'Calls',
    colP50: 'P50',
    colP95: 'P95',
    colErrPct: 'Err%',
    colRetries: 'Retries',
    colAuth: 'Auth',
    colAccess: 'Access',
    colStatus: 'Status',
    colActions: 'Actions',
    noSavedQueriesYet: 'No saved queries yet',
    noSavedQueriesDescription: 'Create a query from the editor to track endpoint health and access metrics.',
    noMatchingQueriesTitle: 'No matching queries/endpoints found.',
    tryDifferentQueryOrEndpointSearch: 'Try a different query or endpoint search.',
    querySearchPlaceholder: 'Search queries...',
  },
  configSections: {
    connection: 'Connection Configuration',
    authentication: 'Authentication Configuration',
    sshTunnel: 'SSH Tunnel Configuration',
    host: 'Host Configuration',
    sslTls: 'SSL / TLS Configuration',
    headers: 'Headers Configuration',
    queryParameters: 'Query Parameters',
    requestBody: 'Request Body Configuration',
    pagination: 'Pagination Configuration',
    graphql: 'GraphQL Query Configuration',
    security: 'Security Options',
    runtime: 'Runtime Preview',
    queryType: 'Query Type',
    customQuery: 'Custom Query',
    customQueryDescription: 'Write and run a custom query for this datasource.',
    addMoreSshHosts: 'Add More SSH Hosts',
    addMoreHosts: 'Add More Hosts',
    addMore: 'Add More',
    headersSpan: 'Headers',
    queryParametersSpan: 'Query Parameters',
    runtimeResponse: 'Response',
    runtimeHeaders: 'Headers',
    runtimeLogs: 'Logs',
    runtimeLinter: 'Linter',
    runtimeState: 'State',
  },
  editor: {
    addQuery: '+ Add Query',
    runQuery: 'Run Query',
    saveQuery: 'Save Query',
    noResultsYet: 'No results yet. Click Run Query.',
    queryRanSuccessfully: 'Query ran successfully.',
    queryUpdatedSuccessfully: '{name} updated successfully.',
    queryAdded: '{name} added to Data Sources.',
    activateDatasourceAndQueryBeforeRunningIt: 'Activate the datasource and query before running it.',
    activateDatasourceBeforeSavingQuery: 'Activate the datasource before saving a query.',
    duplicateQueryNameError: 'A query with this name already exists for this datasource.',
    querySavedSuccessfully: 'Query saved successfully.',
    queryDeletedSuccessfully: '{name} deleted.',
    queryNotFound: 'Query not found.',
    queryInactiveActivateBeforeEditing: '{name} is inactive. Activate it before editing.',
    tabResults: 'Results',
    tabResponse: 'Response',
    tabLogs: 'Logs',
    tabMetadata: 'Metadata',
    deleteQueryTitle: 'Delete Query',
    deleteQueryDescription: 'Delete this saved query? This cannot be undone.',
    deleteDatasourceTitle: 'Delete Datasource',
    deleteDatasourceDescription: 'Delete this datasource and its saved queries? This cannot be undone.',
  },
  saveQueryModal: {
    title: 'Save Query',
    subtitle: 'Store the active query in this datasource so metrics and access history remain visible.',
    queryName: 'Query Name',
    queryNameRequired: 'Query name is required.',
    description: 'Description',
    descriptionOptionalHint: 'Optional',
    optionalDescription: 'Optional description',
    cancel: 'Cancel',
    saveQuery: 'Save Query',
  },
  schemaModal: {
    title: 'Field Mapping Review',
    subtitle: 'Builder loaded the selected datasource columns and suggested a matching field type for each one.',
    countLabel: '{selected} selected / {total} columns',
    fieldTypeLabel: 'Field Type',
    infoText: 'Field types were auto-suggested based on the datasource columns. Required fields are marked with a red star. Please select columns and modify field types if needed.',
    fieldMappingsApplied: 'Field mappings applied successfully.',
    applyFields: 'Apply Fields',
    clearAll: 'Clear All',
    selectAll: 'Select All',
    cancel: 'Cancel',
  },
  queryDetail: {
    openEditor: 'Open Query Editor',
    close: 'Close',
    queryReferenceNotFound: 'Query reference not found',
    usedInTitle: 'Used In',
    notReferencedYet: 'Not referenced yet.',
    detailDatasource: 'Datasource',
    detailQueryType: 'Query Type',
    detailColumns: 'Columns',
    detailPreviewRows: 'Preview Rows',
    detailCalls: 'Calls',
    detailP95: 'P95 Latency',
    detailSubtitle: '{source} · Custom Query',
    datasourceName: 'Datasource Name',
    datasourceNameRequired: 'Datasource name is required.',
    enterDatasourceName: 'Enter datasource name',
  },
  dynamicForm: {
    addMapping: 'Add Mapping',
    deleteMapping: 'Delete',
    mappingTitle: 'Mapping {index}',
    sourcePath: 'Source Path',
    targetField: 'Target Field',
    fieldType: 'Type',
    required: 'Required',
    requestTabTitle: 'Request ({count})',
    responseTabTitle: 'Response ({count})',
  },
  externalApis: {
    selectExternalApiEyebrow: 'Select External API',
    chooseConnector: 'Choose Connector',
    chooseConnectorDescription: 'Select a SaaS integration or custom REST API connector.',
    searchIntegrations: 'Search integrations...',
    back: 'Back',
    externalSystemsEyebrow: 'External Systems',
    externalApisTitle: 'External APIs',
    externalApisDescription: 'Connect SaaS apps and custom APIs to use them in forms, reports, workflows and automations.',
    externalApisInfoCard: 'Each external system shows connection status, authentication type, last sync, usage, and quick actions.',
    searchExternalSystems: 'Search external systems...',
    testAll: 'Test All',
    addIntegration: '+ Add Integration',
    metricStatus: 'Status',
    metricAuth: 'Auth',
    metricLastSync: 'Last Sync',
    metricUsedIn: 'Used In',
    edit: 'Edit',
    test: 'Test',
    sync: 'Sync',
    delete: 'Delete',
    expand: 'Expand',
    collapse: 'Collapse',
    searchResources: 'Search resources...',
    clear: 'Clear',
    colResource: 'Resource',
    colMethod: 'Method',
    colMappedFields: 'Mapped Fields',
    colSyncMode: 'Sync Mode',
    colUsage: 'Usage',
    noIntegrationsFound: 'No integrations found',
    tryDifferentSearchOrFilter: 'Try a different search or filter.',
    noMatchingResourcesFound: 'No matching resources found',
    tryDifferentResourceSearch: 'Try a different resource search.',
    configureEyebrow: 'Configure Integration',
    editSetupPrefix: 'Edit',
    configureSetupPrefix: 'Configure',
    setupDescription: 'Configure authentication and workspace access for this external API integration.',
    cancel: 'Cancel',
    testConfiguration: 'Test Configuration',
    saveChanges: 'Save Changes',
    save: 'Save',
    configurationTestSection: 'Configuration Test',
    deleteIntegrationTitle: 'Delete Integration',
    deleteIntegrationDescription: 'Delete {name}? This cannot be undone.',
    allIntegrationsTested: 'All integrations tested.',
    externalConnectorNotFound: 'External connector not found.',
    inactiveActivateBeforeTesting: '{name} is inactive. Activate it before testing.',
    notConnectedYet: '{name} is not connected yet.',
    testedSuccessfully: '{name} tested successfully.',
    connectionTestedSuccessfully: 'Connection tested successfully.',
    updatedSuccessfully: '{name} updated successfully.',
    savedSuccessfully: '{name} saved successfully.',
    markedActive: '{name} marked active.',
    markedInactive: '{name} marked inactive.',
    syncedSuccessfully: '{name} synced successfully.',
    deleted: '{name} deleted.',
    connectionSuccessful: '{name} connected successfully.',
  },
  messages: {
    externalConnectorNotFound: 'External connector not found.',
    allIntegrationsTested: 'All integrations tested.',
    inactiveActivateBeforeTesting: '{name} is inactive. Activate it before testing.',
    notConnectedYet: '{name} is not connected yet.',
    testedSuccessfully: '{name} tested successfully.',
    connectionTestedSuccessfully: 'Connection tested successfully.',
    updatedSuccessfully: '{name} updated successfully.',
    savedSuccessfully: '{name} saved successfully.',
    markedActive: '{name} marked active.',
    markedInactive: '{name} marked inactive.',
    syncedSuccessfully: '{name} synced successfully.',
    deleted: '{name} deleted.',
    connectionSuccessful: '{name} connected successfully.',
  },
} as const;

