export const DEPLOYER_LANG = {
  auth: {
    brandName: 'Quanta Ops',
    brandSubtitle: 'Deployer Administration',
    signIn: 'Sign In',
    emailAddress: 'Email Address',
    password: 'Password',
    emailPlaceholder: 'admin@quanta-ops.com',
    passwordPlaceholder: '********',
    signInButton: 'Sign In',
    validationError: 'Validation Error',
    validationErrorMessage: 'Please enter both email and password',
    emailRequired: 'Email is required.',
    emailInvalid: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    loginSuccessful: 'Login successful',
    welcomeBack: 'Welcome back, {email}',
  },
  validation: {
    fieldRequired: 'This field is required.',
    emailInvalid: 'Enter a valid email address.',
    checkThisField: 'Check this field.',
  },
  organisations: {
    addModalTitle: 'New Organisation',
    addModalSubtitle: 'Add a new client organisation to the Quanta Ops platform',
    organisationName: 'Organisation Name',
    organisationNamePlaceholder: 'e.g. Acme Corporation',
    entityType: 'Entity Type',
    primaryOwnerEmail: 'Primary Owner Email',
    primaryOwnerEmailPlaceholder: 'owner@company.com',
    billingEmail: 'Billing Email',
    billingEmailPlaceholder: 'billing@company.com',
    additionalAdminUsers: 'Additional Admin Users',
    additionalAdminUsersPlaceholder: 'admin1@co.com, admin2@co.com (optional)',
    cancel: 'Cancel',
    createOrganisation: 'Create Organisation ->',
    noOrganisationSelected: 'No organisation selected',
  },
  audit: {
    eyebrow: 'Traceability',
    title: 'Audit log',
    description: 'Operational audit trail for user actions, system events, and affected entities.',
    colActor: 'Actor',
    colTimestamp: 'Timestamp',
    colActionType: 'Action Type',
    colAffectedEntity: 'Affected Entity',
    colDescription: 'Description',
    noAuditRecords: 'No audit records',
    noAuditRecordsDescription: 'System and user activity for the selected organisation will appear here.',
  },
  billing: {
    eyebrow: 'Billing',
    movedTitle: 'Billing has moved into settings',
    movedDescription: 'Invoices, payments, tax settings, and organisation billing details are now managed from the settings area.',
    openSettings: 'Open settings',
  },
  dashboard: {
    eyebrow: 'Overview',
    title: 'Dashboard',
    newApplication: 'New Application',
    selectedOrganisationLabel: 'Selected organisation',
    heroDescription: 'Enterprise deployment overview with current application health, operational activity, and portfolio readiness.',
    liveWorkspaces: '{count} live workspaces',
    lastSynced: 'Last synced 4 min ago',
    appInstancesEyebrow: 'Application instances',
    appInstancesTitle: 'Application instances',
    appInstancesDescription: 'Review deployment health, user activity, and operational readiness across active environments.',
    searchApps: 'Search apps...',
    deployCta: 'Deploy a New Application',
    metricUsers: 'Users',
    metricLatency: 'Latency',
    metricResume: 'Resume',
    metricPeriod: 'Period',
    builder: 'Builder',
    preview: 'Preview',
    activate: 'Activate',
    deleteApplication: 'Delete application',
    noApplications: 'No applications',
    noApplicationsDescription: 'Create the first application for this organisation to start tracking deployed workloads.',
    addApplicationTitle: 'New Application',
    addApplicationSubtitle: 'Deploy a new application under {organisationName}',
    appName: 'Application Name',
    appNamePlaceholder: 'e.g. HR Management System',
    appType: 'Application Type',
    appPrimaryOwner: 'Primary Owner',
    appDescription: 'Description',
    appDescriptionPlaceholder: 'What does this application do?',
    superAdminsLabel: 'Super Admins (comma-separated emails)',
    superAdminsPlaceholder: 'admin@acme.co, manager@acme.co',
    adminsLabel: 'Admins (comma-separated emails)',
    adminsPlaceholder: 'developer@acme.co',
    cancel: 'Cancel',
    createApplication: 'Create Application',
    selectOrganisationFirst: 'Please select an organisation first.',
    unableToOpenBuilder: 'Unable to open Builder for this application.',
  },
  notifications: {
    panelTitle: 'Notifications',
    panelSubtitle: 'Alerts and activity',
    close: 'Close',
  },
  settings: {
    breadcrumb: 'Organizations / {organisationName} / Settings',
    title: 'Settings',
    tabOrganisation: 'Organisation',
    tabBillingTax: 'Billing & Tax',
    tabInvoices: 'Invoices',
    tabPayments: 'Payments',
    orgDetailsLabel: 'Organisation Details',
    orgEntityName: 'Entity Name',
    orgEntityNameHint: 'Used on all invoices and communications',
    orgRegisteredAddress: 'Registered Address',
    orgType: 'Organisation Type',
    orgStatus: 'Organisation Status',
    orgSaveChanges: 'Save Changes',
    orgPrimaryOwnerLabel: 'Primary Owner',
    orgOwnerName: 'Owner Name',
    orgOwnerEmail: 'Owner Email',
    orgOwnerPhone: 'Owner Phone',
    orgTransferOwnership: 'Transfer Ownership',
    orgTransferButton: 'Transfer to Another User',
    orgAdminUsersLabel: 'Admin Users',
    orgAddAdmin: '+ Add Admin',
    orgSummaryLabel: 'Organisation Summary',
    orgBuilderAccessLabel: 'App Builder Access',
    orgBuilderAccessDescription: 'Open the App Builder to create and configure deployed applications for this organisation.',
    orgOpenBuilder: 'Open App Builder',
    orgDangerZone: 'Danger Zone',
    orgDangerDescription: 'Permanently delete this organisation and all its data. Irreversible.',
    orgDangerConfirmPlaceholder: 'Type organisation name...',
    orgDeleteButton: 'Delete Organisation',
    inviteAdminTitle: 'Invite Team Member',
    inviteAdminSubtitle: 'Send an invitation to your organisation',
    taxRegistrationLabel: 'Tax Registration Numbers',
    gstNumber: 'GST Number',
    gstHint: 'Format: 15-character GSTIN - Validated on save',
    tanNumber: 'TAN Number',
    tanHint: '10-character TAN',
    panNumber: 'PAN Number',
    panHint: '10-character PAN',
    saveTaxDetails: 'Save Tax Details',
    billingContactLabel: 'Billing Contact',
    billingContactName: 'Billing Contact Name',
    billingEmail: 'Billing Email',
    saveBillingDetails: 'Save Billing Details',
    currentPlanLabel: 'Current Plan',
    currentPlanPlan: 'Plan',
    currentPlanCycle: 'Billing Cycle',
    currentPlanNextInvoice: 'Next Invoice',
    currentPlanPaymentMethod: 'Payment Method',
    upgradePlan: 'Upgrade Plan',
    invoicesFound: '{count} invoices found',
    exportAll: 'Export All',
    colInvoiceNumber: 'Invoice #',
    colDateRaised: 'Date Raised',
    colBillingPeriod: 'Billing Period',
    colAmount: 'Amount',
    colStatus: 'Status',
    colPdf: 'PDF',
    noInvoices: 'No invoices',
    noInvoicesDescription: 'Invoices for the selected organisation will appear here once billing starts.',
    invoiceDetailTitle: 'Invoice Detail',
    invoiceDetailNumber: 'Invoice number',
    invoiceDetailDate: 'Invoice date',
    invoiceDetailBillingPeriod: 'Billing period',
    invoiceDetailAmount: 'Amount',
    invoiceDetailStatus: 'Status',
    invoiceDetailClose: 'Close detail',
    markAsPaidTitle: 'Mark as Paid',
    markAsPaidCancel: 'Cancel',
    markAsPaidConfirm: 'Confirm payment',
    outstandingBalance: 'Outstanding Balance',
    recordPayment: 'Record Payment',
    colPaymentDate: 'Date',
    colPaymentReference: 'Reference #',
    colPaymentAmount: 'Amount',
    colPaymentMethod: 'Method',
    colPaymentInvoice: 'Invoice',
    noPaymentsRecorded: 'No payments recorded',
    noPaymentsDescription: 'Manual and offline payments will appear here after they are recorded.',
    recordPaymentModalTitle: 'Record Payment',
    recordPaymentModalSubtitle: 'Manually record an offline or bank-transfer payment',
    invoiceField: 'Invoice',
    amountPaid: 'Amount Paid',
    paymentDate: 'Payment Date',
    referenceNumber: 'Reference Number',
    referencePlaceholder: 'Bank ref / UTR number',
    paymentMethodField: 'Payment Method',
    recordPaymentCancel: 'Cancel',
    recordPaymentSubmit: 'Record Payment',
    selectOrganisationBeforeDeleting: 'Select an organisation before deleting.',
    organisationDeleted: 'Organisation deleted.',
    deleteOrganisationTitle: 'Delete organisation',
    deleteOrganisationDescription: 'Delete {name}? This cannot be undone.',
  },
  usage: {
    breadcrumb: 'Organizations / {organisationName} / Usage',
    title: 'Usage',
    layer1Label: 'Layer 1',
    cumulativeSummaryTitle: 'Cumulative Summary',
    cumulativeSummaryDescription: 'All data sources & endpoints across all applications',
    layer2Label: 'Layer 2',
    dataSourcesTitle: 'Data Sources',
    dataSourcesDescription: 'Click "Expand" to view endpoints for that source',
    layer3Label: 'Layer 3',
    endpointsForSource: 'Endpoints for {source}',
    readCount: 'Read: {count}',
    writeCount: 'Write: {count}',
    colSource: 'Source',
    colApplication: 'Application',
    colType: 'Type',
    colAvailPct: 'Avail %',
    colP95Lat: 'P95 Lat',
    colRpm: 'RPM',
    colErrors: 'Errors',
    colAuth: 'Auth',
    colJobs: 'Jobs',
    colEps: 'EPS',
    colActions: 'Actions',
    colEndpoint: 'Endpoint',
    colMethod: 'Method',
    colCalls: 'Calls',
    colP50: 'P50',
    colP95: 'P95',
    colErrPct: 'Err%',
    colDup: 'Dup',
    colRetries: 'Retries',
    colAccess: 'Access',
    colDetail: 'Detail',
    expand: 'Expand',
    collapse: 'Collapse',
    logs: 'Logs',
    detail: 'Detail',
    noUsageSources: 'No usage sources',
    noUsageSourcesDescription: 'Usage and health metrics will appear here once the selected organisation has tracked data sources.',
    noEndpoints: 'No endpoints',
    noEndpointsDescription: 'Endpoint metrics will appear here when this data source receives traffic.',
  },
  users: {
    breadcrumb: 'Organizations / {organisationName} / Users',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    passwordReset: 'Password reset email sent to {email}',
    teamMember: 'Team Member',
    notProvided: 'Not provided',
    searchPlaceholder: 'Search by name or email...',
    noMatchingUsersTitle: 'No matching users',
    noMatchingUsersDescription: 'Adjust the local search or active-state filters to restore matching records.',
    emailAddress: 'Email Address',
    firstName: 'First Name',
    lastName: 'Last Name',
    phoneNumber: 'Phone Number',
    department: 'Department',
    profilePhoto: 'Profile Photo',
    uploadPhotoOptional: 'Upload photo (optional)',
    userEmailPlaceholder: 'user@company.com',
    phoneNumberPlaceholder: '+91 98765 43210',
    departmentPlaceholder: 'e.g. Operations',
    addUser: 'Add User',
    addNewUserTitle: 'Add New User',
    editUser: 'Edit User',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    edit: 'Edit',
    reset: 'Reset',
    user: 'User',
    usersPageTitle: 'Users',
    usersPageDescription: "Manage user profiles and account access. Application permissions and roles are configured inside each app's Builder.",
    userDetailsOnlyHeading: 'User details only.',
    userDetailsOnlyDescription: "Application access, page permissions, and roles are configured inside each application's Builder -> Deployment -> User Management. You cannot add a user to an application without first registering them here.",
    organisationNotSelected: 'No organisation selected',
    accountStatus: 'Account Status',
    accountStatusNote: 'Disabling logs the user out immediately',
    sendPasswordReset: 'Send Password Reset',
    passwordResetTitle: 'Password Reset',
    passwordResetSubtitle: 'Send a secure reset link to this user',
    passwordResetPrompt: 'Send a password reset email to',
    passwordResetExplanation: "The link will expire automatically and the user's current session will remain active until they reset their password.",
    sendReset: 'Send Reset',
    resetNote: '"Reset" sends a password reset email instantly. "Disable" immediately blocks login without deleting data.',
    updateProfileDetails: 'Update profile details for {name}',
    registerUserTo: 'Register a user to {organisation}',
    addUserModalNote: "No role is assigned here. Roles and application access are configured inside each app's Builder -> Deployment -> User Management.",
    emailAndPhone: 'Email & Phone',
    status: 'Status',
    lastLogin: 'Last Login',
    sessionHours: 'Session Hrs',
    actions: 'Actions',
    disable: 'Disable',
    enable: 'Enable',
  },
} as const;

