import { WorkflowExecutionSummary, WorkflowTriggerType } from '@qo/models';
import {
  WorkflowActionButtonListItem,
  WorkflowEventListItem,
  WorkflowFunctionCardItem,
  WorkflowScheduleListItem,
} from './workflow-builder-ui.model';
import { WORKFLOW_LANGUAGE } from '../services/workflow-language';

const DEMO = WORKFLOW_LANGUAGE.demoData;

export function createWorkflowRuns(
  workflowId: string,
  triggerType: WorkflowTriggerType,
  count: number
): WorkflowExecutionSummary[] {
  return Array.from({ length: count }, (_, index) => ({
    id: `${workflowId}_run_${index + 1}`,
    workflowId,
    celeryTaskId: `celery_${workflowId}_${index + 1}`,
    triggerType,
    status: index === 0 ? 'completed' : index === 1 ? 'running' : 'pending',
    startedAt: `2026-04-22T0${index + 7}:58:00.000Z`,
    finishedAt: index === 0 ? `2026-04-22T0${index + 7}:58:03.000Z` : null,
  }));
}

export const WORKFLOW_EVENT_ROWS: WorkflowEventListItem[] = [
  {
    id: 'evt_employee_status',
    event: DEMO.events.employeeStatusChanged,
    trigger: DEMO.events.fieldChange,
    source: DEMO.events.employeeStatusSource,
    lastRun: DEMO.events.twoHoursAgo,
    status: 'active',
  },
  {
    id: 'evt_webhook_sync',
    event: DEMO.events.inboundWebhookSync,
    trigger: DEMO.events.webhookPost,
    source: DEMO.events.externalAts,
    lastRun: DEMO.events.fiveHoursAgo,
    status: 'active',
  },
  {
    id: 'evt_salary_update',
    event: DEMO.events.salaryUpdateAlert,
    trigger: DEMO.events.fieldChange,
    source: DEMO.events.salarySource,
    lastRun: DEMO.events.oneDayAgo,
    status: 'active',
  },
  {
    id: 'evt_leave_approved',
    event: DEMO.events.leaveApprovedTrigger,
    trigger: DEMO.events.fieldChange,
    source: DEMO.events.leaveStatusSource,
    lastRun: DEMO.events.twoDaysAgo,
    status: 'paused',
  },
  {
    id: 'evt_new_hire_onboarded',
    event: 'New Hire Onboarded',
    trigger: DEMO.events.fieldChange,
    source: 'employees · onboarding_status',
    lastRun: '3h ago',
    status: 'active',
  },
  {
    id: 'evt_asset_request_raised',
    event: 'Asset Request Raised',
    trigger: DEMO.events.fieldChange,
    source: 'asset_requests · status',
    lastRun: '6h ago',
    status: 'active',
  },
  {
    id: 'evt_performance_review_submitted',
    event: 'Performance Review Submitted',
    trigger: DEMO.events.fieldChange,
    source: 'performance_reviews · overall_rating',
    lastRun: DEMO.events.oneDayAgo,
    status: 'active',
  },
  {
    id: 'evt_it_ticket_escalated',
    event: 'IT Ticket Escalated',
    trigger: DEMO.events.fieldChange,
    source: 'it_tickets · severity',
    lastRun: '45m ago',
    status: 'active',
  },
];

export const WORKFLOW_SCHEDULE_ROWS: WorkflowScheduleListItem[] = [
  {
    id: 'sch_daily_hr_sync',
    workflowName: DEMO.schedules.dailyHrSync,
    frequencyLabel: DEMO.schedules.everyDayAtNine,
    scopeLabel: DEMO.schedules.hrMasterData,
    nextRunAt: DEMO.schedules.todayNine,
    enabled: true,
  },
  {
    id: 'sch_leave_digest',
    workflowName: DEMO.schedules.weeklyLeaveDigest,
    frequencyLabel: DEMO.schedules.everyMondayAtEightThirty,
    scopeLabel: DEMO.schedules.leaveRequests,
    nextRunAt: DEMO.schedules.mondayEightThirty,
    enabled: false,
  },
  {
    id: 'sch_payroll_cutoff',
    workflowName: DEMO.schedules.payrollCutoffCheck,
    frequencyLabel: DEMO.schedules.everyFridayAtFiveThirty,
    scopeLabel: DEMO.schedules.payrollOperations,
    nextRunAt: DEMO.schedules.fridayFiveThirty,
    enabled: true,
  },
  {
    id: 'sch_attendance_rollup',
    workflowName: DEMO.schedules.attendanceRollup,
    frequencyLabel: DEMO.schedules.everyWeekdayAtSix,
    scopeLabel: DEMO.schedules.attendanceLogs,
    nextRunAt: DEMO.schedules.todaySix,
    enabled: true,
  },
  {
    id: 'sch_performance_review_reminder',
    workflowName: 'Performance Review Reminder',
    frequencyLabel: 'Every 1st of month at 09:00',
    scopeLabel: 'Performance Reviews',
    nextRunAt: 'Jul 1, 09:00',
    enabled: true,
  },
  {
    id: 'sch_recruitment_pipeline_sync',
    workflowName: 'Recruitment Pipeline Sync',
    frequencyLabel: 'Every Tuesday at 10:00',
    scopeLabel: 'Candidate Pipeline',
    nextRunAt: 'Tue, 10:00',
    enabled: true,
  },
  {
    id: 'sch_it_ticket_sla_check',
    workflowName: 'IT Ticket SLA Check',
    frequencyLabel: 'Every 4 hours',
    scopeLabel: 'IT Support Tickets',
    nextRunAt: 'Today, 20:00',
    enabled: true,
  },
  {
    id: 'sch_travel_expense_digest',
    workflowName: 'Travel Expense Weekly Digest',
    frequencyLabel: 'Every Friday at 08:00',
    scopeLabel: 'Travel Expense Claims',
    nextRunAt: 'Fri, 08:00',
    enabled: false,
  },
];

export const WORKFLOW_ACTION_BUTTON_ROWS: WorkflowActionButtonListItem[] = [
  {
    id: 'act_approve_user',
    actionName: DEMO.actionButtons.approveUser,
    linkedWorkflow: DEMO.actionButtons.employeeApprovalFlow,
    scope: WORKFLOW_LANGUAGE.options.scope.report,
    source: 'rpt.users',
    usedIn: DEMO.actionButtons.usersGrid,
    status: 'active',
  },
  {
    id: 'act_send_reminder',
    actionName: DEMO.actionButtons.sendReminder,
    linkedWorkflow: DEMO.actionButtons.leaveReminderFlow,
    scope: WORKFLOW_LANGUAGE.options.scope.page,
    source: 'page.leave',
    usedIn: DEMO.actionButtons.leavePage,
    status: 'active',
  },
  {
    id: 'act_archive_item',
    actionName: DEMO.actionButtons.archiveItem,
    linkedWorkflow: DEMO.actionButtons.archiveFlow,
    scope: WORKFLOW_LANGUAGE.options.scope.global,
    source: 'page.hr',
    usedIn: DEMO.actionButtons.fourPlaces,
    status: 'draft',
  },
  {
    id: 'act_sync_candidate',
    actionName: DEMO.actionButtons.syncCandidate,
    linkedWorkflow: DEMO.actionButtons.candidateSyncFlow,
    scope: WORKFLOW_LANGUAGE.options.scope.report,
    source: 'rpt.recruitment',
    usedIn: DEMO.actionButtons.hiringBoard,
    status: 'active',
  },
  {
    id: 'act_approve_leave',
    actionName: 'Approve Leave',
    linkedWorkflow: 'Leave Approval Flow',
    scope: WORKFLOW_LANGUAGE.options.scope.report,
    source: 'rpt.leave_summary',
    usedIn: 'Leave Summary Report',
    status: 'active',
  },
  {
    id: 'act_escalate_ticket',
    actionName: 'Escalate Ticket',
    linkedWorkflow: 'IT Ticket Escalation Flow',
    scope: WORKFLOW_LANGUAGE.options.scope.report,
    source: 'rpt.it_tickets',
    usedIn: 'IT Support Tickets Report',
    status: 'active',
  },
  {
    id: 'act_generate_offer_letter',
    actionName: 'Generate Offer Letter',
    linkedWorkflow: 'Offer Letter Generation Flow',
    scope: WORKFLOW_LANGUAGE.options.scope.report,
    source: 'rpt.recruitment',
    usedIn: 'Recruitment Pipeline Report',
    status: 'draft',
  },
  {
    id: 'act_initiate_exit',
    actionName: 'Initiate Exit Process',
    linkedWorkflow: 'Employee Exit Workflow',
    scope: WORKFLOW_LANGUAGE.options.scope.global,
    source: 'page.hr',
    usedIn: 'HR Dashboard',
    status: 'active',
  },
];

export const WORKFLOW_FUNCTION_CARDS: WorkflowFunctionCardItem[] = [
  {
    id: 'fn_leave_payload',
    name: DEMO.functions.formatLeavePayload,
    language: 'javascript',
    description: DEMO.functions.formatLeavePayloadDescription,
    code: 'function transform(input) {\n  return { ...input, source: "workflow-builder" };\n}',
    updatedAt: '2026-04-22T08:20:00.000Z',
  },
  {
    id: 'fn_employee_key',
    name: DEMO.functions.buildEmployeeKey,
    language: 'python',
    description: DEMO.functions.buildEmployeeKeyDescription,
    code: 'def build_key(record):\n    return f"{record.get(\'department\', \'na\')}-{record.get(\'employee_code\', \'unknown\')}"',
    updatedAt: '2026-04-20T06:10:00.000Z',
  },
  {
    id: 'fn_webhook_signature',
    name: DEMO.functions.verifyWebhookSignature,
    language: 'javascript',
    description: DEMO.functions.verifyWebhookSignatureDescription,
    code: 'function verifySignature(payload, signature) {\n  return Boolean(payload && signature);\n}',
    updatedAt: '2026-04-19T09:30:00.000Z',
  },
  {
    id: 'fn_leave_summary',
    name: DEMO.functions.summarizeLeaveWindow,
    language: 'python',
    description: DEMO.functions.summarizeLeaveWindowDescription,
    code: 'def summarize_leave(request):\n    return f"{request.get(\'employee\', \'Unknown\')} · {request.get(\'days\', 0)} days"',
    updatedAt: '2026-04-18T07:45:00.000Z',
  },
  {
    id: 'fn_notify_manager',
    name: 'Notify Manager on Leave',
    language: 'javascript',
    description: 'Send a structured notification email to a manager when a leave request is raised.',
    code: 'async function notifyManager(record) {\n  const msg = `Leave request from ${record.employee_name} (${record.days} days)`;\n  await sendEmail({ to: record.manager_email, subject: "Leave Request", body: msg });\n}',
    updatedAt: '2026-05-10T11:00:00.000Z',
  },
  {
    id: 'fn_calculate_travel_reimbursement',
    name: 'Calculate Travel Reimbursement',
    language: 'python',
    description: 'Apply travel policy rules and return the approved reimbursement amount.',
    code: 'def calc_reimbursement(claim):\n    limits = {"Flight": 20000, "Train": 5000, "Cab / Taxi": 3000}\n    cap = limits.get(claim.get("mode_of_transport", ""), 2000)\n    return min(float(claim.get("total_amount", 0)), cap)',
    updatedAt: '2026-05-22T09:15:00.000Z',
  },
  {
    id: 'fn_generate_employee_id',
    name: 'Generate Employee ID',
    language: 'javascript',
    description: 'Create a sequential EMP-XXXX code for newly onboarded employees.',
    code: 'function generateEmpId(sequence) {\n  return `EMP-${String(sequence).padStart(4, "0")}`;\n}',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'fn_sla_breach_check',
    name: 'SLA Breach Checker',
    language: 'javascript',
    description: 'Return true if an IT support ticket has breached its SLA window.',
    code: 'function isSlaBreach(ticket) {\n  const slaHours = { "P1 - Critical": 4, "P2 - High": 8, "P3 - Medium": 24, "P4 - Low": 72 };\n  const hours = (Date.now() - new Date(ticket.issue_date).getTime()) / 3600000;\n  return hours > (slaHours[ticket.severity] ?? 24);\n}',
    updatedAt: '2026-06-10T14:30:00.000Z',
  },
];
