import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { provideRouter } from '@angular/router';
import { signal } from '@angular/core';
import { DeploymentPageComponent } from '@builder/features/deployment/containers/deployment-page.component';
import { DeploymentFacadeService } from '@builder/features/deployment/facades/deployment.facade';
import { DeploymentExportService } from '@builder/features/deployment/services/deployment-export.service';

function buildFacadeMock(): Partial<DeploymentFacadeService> {
  return {
    showPreview: signal(false),
    previewFullScreen: signal(false),
    runtimeMode: signal('preview'),
    saveState: signal('idle'),
    primaryClickBehaviour: signal('selectors'),
    topDependencySource: signal('left'),
    showPreviewColumnDropdown: signal(false),
    showPreviewFiltersPanel: signal(false),
    showPreviewSortPanel: signal(false),
    showPreviewToolsPanel: signal(false),
    showPreviewEmployeeModal: signal(false),
    previewSearchQuery: signal(''),
    previewFilters: signal({ activeOnly: false, department: '', joinedFrom: '', joinedTo: '', newJoinersOnly: false, onLeaveOnly: false }),
    previewSortMode: signal('name-asc'),
    previewViewMode: signal('grid'),
    selectedEnvironmentId: signal(''),
    customDomain: signal(''),
    basePath: signal(''),
    leftHeaderOptions: signal([]),
    rightHeaderOptions: signal([]),
    primaryPages: signal([]),
    leftPageGroups: signal([]),
    topPageGroups: signal([]),
    footerOptions: signal([]),
    leftFooterButtons: signal([]),
    rightFooterButtons: signal([]),
    workspaceTypes: signal([]),
    environments: signal([]),
    activeLayoutPayload: signal({ layout: { header: { leftOptions: [], rightOptions: [] }, footer: { leftFooter: { buttons: [] }, rightFooter: { buttons: [] } }, navigation: { primaryPages: [], leftPagesByPrimaryId: {}, subPagesByLeftPageId: {}, topTabPagesBySourceId: {} }, workspace: { workspaceTypes: [] }, pageTargets: {} } } as never),
    layoutJson: signal('{}'),
    saveButtonLabel: signal('Save & Deploy'),
    runtimeTitle: signal('Deployed App Layout'),
    runtimeEyebrow: signal('Preview'),
    runtimeLeftFooterButtons: signal([]),
    runtimeRightFooterButtons: signal([]),
    previewPrimaryPages: signal([]),
    selectedPreviewPrimaryPage: signal(null),
    previewNavigationPages: signal([]),
    selectedPreviewLeftPage: signal(null),
    previewSubPages: signal([]),
    selectedPreviewSubPage: signal(null),
    previewTopTabs: signal([]),
    selectedPreviewTopTab: signal(null),
    previewDataset: signal({ columns: [], rows: [] }),
    previewDepartments: signal([]),
    pageTargets: signal({}),
    openConfigPageId: signal(null),
    activeShowcaseReports: signal([]),
    activeShowcasePages: signal([]),
    activeShowcaseForms: signal([]),
    pageTargetLabels: signal({}),
    currentPageTargetType: signal(null),
    currentPageTargetName: signal(''),
    showcasePanelOpen: signal(false),
    showcaseActiveModule: signal('forms'),
    showcaseForms: signal([]),
    showcaseReports: signal([]),
    showcasePages: signal([]),
    selectedShowcaseForm: signal(null),
    showFormRuntimeModal: signal(false),
    formRuntimeValues: signal({}),
    formRuntimeErrors: signal({}),
    formRuntimeSubmitting: signal(false),
    workflowExecutionOpen: signal(false),
    workflowExecutionSteps: signal([]),
    workflowExecutionCurrentStep: signal(0),
    workflowExecutionComplete: signal(false),
    workflowExecutionFormName: signal(''),
    currentPageWidgets: signal([]),
    currentPageCanvasHeight: signal(300),
    currentTargetForm: signal(null),
    setPrimaryClickBehaviour: jasmine.createSpy('setPrimaryClickBehaviour'),
    areOtherPageSelectorsEnabled: jasmine.createSpy('areOtherPageSelectorsEnabled').and.returnValue(true),
    setTopDependencySource: jasmine.createSpy('setTopDependencySource'),
    addPrimaryPage: jasmine.createSpy('addPrimaryPage'),
    removePrimaryPage: jasmine.createSpy('removePrimaryPage'),
    renamePrimaryPage: jasmine.createSpy('renamePrimaryPage'),
    reorderPrimaryPages: jasmine.createSpy('reorderPrimaryPages'),
    reorderLeftPages: jasmine.createSpy('reorderLeftPages'),
    reorderLeftSubPages: jasmine.createSpy('reorderLeftSubPages'),
    addLeftPage: jasmine.createSpy('addLeftPage'),
    renameLeftPage: jasmine.createSpy('renameLeftPage'),
    removeLeftPage: jasmine.createSpy('removeLeftPage'),
    addLeftSubPage: jasmine.createSpy('addLeftSubPage'),
    renameLeftSubPage: jasmine.createSpy('renameLeftSubPage'),
    removeLeftSubPage: jasmine.createSpy('removeLeftSubPage'),
    addTopTabPage: jasmine.createSpy('addTopTabPage'),
    renameTopTabPage: jasmine.createSpy('renameTopTabPage'),
    removeTopTabPage: jasmine.createSpy('removeTopTabPage'),
    toggleHeaderOption: jasmine.createSpy('toggleHeaderOption'),
    toggleFooterOption: jasmine.createSpy('toggleFooterOption'),
    selectWorkspaceType: jasmine.createSpy('selectWorkspaceType'),
    selectEnvironment: jasmine.createSpy('selectEnvironment'),
    updateCustomDomain: jasmine.createSpy('updateCustomDomain'),
    updateBasePath: jasmine.createSpy('updateBasePath'),
    addFooterButton: jasmine.createSpy('addFooterButton'),
    renameFooterButton: jasmine.createSpy('renameFooterButton'),
    removeFooterButton: jasmine.createSpy('removeFooterButton'),
    saveDeploymentLayout: jasmine.createSpy('saveDeploymentLayout'),
    openPreview: jasmine.createSpy('openPreview'),
    openDeployedApp: jasmine.createSpy('openDeployedApp'),
    closePreview: jasmine.createSpy('closePreview'),
    selectPreviewLeftPage: jasmine.createSpy('selectPreviewLeftPage'),
    selectPreviewSubPage: jasmine.createSpy('selectPreviewSubPage'),
    selectPreviewTopTab: jasmine.createSpy('selectPreviewTopTab'),
    selectPreviewPage: jasmine.createSpy('selectPreviewPage'),
    togglePreviewColumnDropdown: jasmine.createSpy('togglePreviewColumnDropdown'),
    previewTabRowCount: jasmine.createSpy('previewTabRowCount').and.returnValue(0),
    updatePreviewSearchQuery: jasmine.createSpy('updatePreviewSearchQuery'),
    togglePreviewFiltersPanel: jasmine.createSpy('togglePreviewFiltersPanel'),
    closePreviewFiltersPanel: jasmine.createSpy('closePreviewFiltersPanel'),
    togglePreviewFilter: jasmine.createSpy('togglePreviewFilter'),
    updatePreviewDepartmentFilter: jasmine.createSpy('updatePreviewDepartmentFilter'),
    updatePreviewJoinedFilter: jasmine.createSpy('updatePreviewJoinedFilter'),
    applyPreviewFilters: jasmine.createSpy('applyPreviewFilters'),
    setPreviewSortMode: jasmine.createSpy('setPreviewSortMode'),
    togglePreviewSortPanel: jasmine.createSpy('togglePreviewSortPanel'),
    closePreviewSortPanel: jasmine.createSpy('closePreviewSortPanel'),
    setPreviewViewMode: jasmine.createSpy('setPreviewViewMode'),
    togglePreviewToolsPanel: jasmine.createSpy('togglePreviewToolsPanel'),
    closePreviewToolsPanel: jasmine.createSpy('closePreviewToolsPanel'),
    openPreviewEmployeeModal: jasmine.createSpy('openPreviewEmployeeModal'),
    closePreviewEmployeeModal: jasmine.createSpy('closePreviewEmployeeModal'),
    setPageTarget: jasmine.createSpy('setPageTarget'),
    clearPageTarget: jasmine.createSpy('clearPageTarget'),
    togglePageConfig: jasmine.createSpy('togglePageConfig'),
    closePageConfig: jasmine.createSpy('closePageConfig'),
    openShowcasePanel: jasmine.createSpy('openShowcasePanel'),
    closeShowcasePanel: jasmine.createSpy('closeShowcasePanel'),
    toggleShowcasePanel: jasmine.createSpy('toggleShowcasePanel'),
    setShowcaseModule: jasmine.createSpy('setShowcaseModule'),
    openFormRuntime: jasmine.createSpy('openFormRuntime'),
    openPrimaryForm: jasmine.createSpy('openPrimaryForm'),
    closeFormRuntime: jasmine.createSpy('closeFormRuntime'),
    updateFormFieldValue: jasmine.createSpy('updateFormFieldValue'),
    submitFormRuntime: jasmine.createSpy('submitFormRuntime'),
    closeWorkflowExecution: jasmine.createSpy('closeWorkflowExecution'),
  };
}

describe('DeploymentPageComponent', () => {
  let component: DeploymentPageComponent;
  let fixture: ComponentFixture<DeploymentPageComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [DeploymentPageComponent],
      providers: [
        provideRouter([]),
        provideNoopAnimations(),
        { provide: DeploymentFacadeService, useValue: buildFacadeMock() },
        { provide: DeploymentExportService, useValue: jasmine.createSpyObj('DeploymentExportService', ['exportCsv', 'exportPdf', 'exportJson']) },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(DeploymentPageComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
